# See https://cloud.google.com/cloud-build/docs/build-config

timeout: 1800s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20200422-b25d964'
    entrypoint: bash
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - GIT_COMMIT=$_GIT_TAG
      - REGISTRY=gcr.io/k8s-staging-ingress-nginx
      - REPO_INFO=https://github.com/kubernetes/ingress-nginx
      - HOME=/root
      - USER=root
    args:
    - -c
    - |
      gcloud auth configure-docker \
      && make release
substitutions:
  _GIT_TAG: "12345"
  _PULL_BASE_REF: "master"
