name: Release

on:
  watch:
    types: [started]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.actor == 'mstavrev'
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish Nginx image
        shell: bash
        run: |
          cd images/nginx-1.25 && make push

      - name: Build and publish Nginx-controller image
        shell: bash
        run: |
          make release
