name: Release

on:
  watch:
    types: [started]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.actor == 'mstavrev'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PERSONAL_TOKEN }}

      - name: Build and publish Nginx image
        shell: bash
        run: |
          cd images/nginx && make push

      - name: Build and publish Nginx-controller image
        shell: bash
        run: |
          make release
