name: Release

on:
  watch:
    types: [started]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.actor == 'mstavrev'
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PERSONAL_TOKEN }}

      - name: Build and publish Nginx image
        shell: bash
        run: |
          cd images/nginx && make push

      - name: Build and publish Nginx-controller image
        shell: bash
        run: |
          make release
